# Generated by Django 5.0.6 on 2024-06-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('concepto', models.CharField(max_length=200)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('ganancia_28', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('ganancia_14', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('publicidad', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('inversion', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('diezmo', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
            ],
        ),
    ]
